apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: ollama-prometheus-scaler
  labels:
    app: ollama
spec:
  scaleTargetRef:
    name: ollama
    kind: Deployment
  pollingInterval: 5
  cooldownPeriod: 30
  minReplicaCount: 1
  maxReplicaCount: 3
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleUp:
          stabilizationWindowSeconds: 0
          selectPolicy: Max
          policies:
            - type: Pods
              value: 1
              periodSeconds: 15
            - type: Percent
              value: 100
              periodSeconds: 15
        scaleDown:
          stabilizationWindowSeconds: 30
          selectPolicy: Max
          policies:
            - type: Percent
              value: 100
              periodSeconds: 15
  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://prometheus.default.svc.cluster.local:9090
        metricName: gateway_llm_active_requests_sum
        threshold: "2"
        query: sum(gateway_llm_active_requests)
